"""Declarative base and reusable column mixins.

Every tenant-scoped table gets its RLS policy from the migration, not from
these mixins — the mixin only supplies the `tenant_id` *column*. See
app/db/migrations/versions/0001_initial_schema_rls.py for the policies.
"""
import uuid
from datetime import datetime

from sqlalchemy import func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class UUIDPkMixin:
    """UUID primary key, generated by Postgres (gen_random_uuid(), built into
    Postgres 13+ core — no pgcrypto extension needed)."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class CreatedAtMixin:
    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), nullable=False
    )


# NOTE: tenant_id is declared directly on each tenant-scoped model rather
# than via a shared mixin. SQLAlchemy mixin columns need `declared_attr` to
# avoid sharing one Column object across mapped classes, and for a column
# this security-critical, explicit-per-model is worth the few extra lines.
# Every tenant-scoped table's tenant_id MUST have a matching RLS policy in
# the migration — enforced by tests/test_rls.py, not by anything in Python.
