"""Declarative base and reusable column mixins.

Every tenant-scoped table gets its RLS policy from the migration, not from
these mixins — the mixin only supplies the `tenant_id` *column*. See
app/db/migrations/versions/0001_initial_schema_rls.py for the policies.
"""
import enum
import uuid
from datetime import datetime
from typing import TypeVar

from sqlalchemy import Enum, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


_E = TypeVar("_E", bound=enum.Enum)


def pg_enum(enum_cls: type[_E], name: str) -> Enum:
    """A Postgres native enum column bound to a Python str-enum, matching
    the DB's actual values.

    Without values_callable, SQLAlchemy's Enum type binds/reads using the
    Python enum MEMBER NAME (e.g. "AI_GENERATION"), not its .value (e.g.
    "ai_generation") — even when the enum also subclasses str. The
    Postgres native enum types created in the migrations only have the
    lowercase .value strings, so an ORM insert through a plain
    Enum(SomeEnum, ...) column fails with "invalid input value for enum"
    the first time anything actually inserts through it. Raw-SQL inserts
    (as tests/test_rls.py's fixtures use) never exercise this path at
    all, which is exactly how this sat undetected through Phase 1 — the
    first ORM-level insert through an enum column was Phase 2's
    record_usage_event().
    """
    return Enum(enum_cls, name=name, native_enum=True, values_callable=lambda cls: [e.value for e in cls])


class UUIDPkMixin:
    """UUID primary key, generated by Postgres (gen_random_uuid(), built into
    Postgres 13+ core — no pgcrypto extension needed)."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class CreatedAtMixin:
    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), nullable=False
    )


# NOTE: tenant_id is declared directly on each tenant-scoped model rather
# than via a shared mixin. SQLAlchemy mixin columns need `declared_attr` to
# avoid sharing one Column object across mapped classes, and for a column
# this security-critical, explicit-per-model is worth the few extra lines.
# Every tenant-scoped table's tenant_id MUST have a matching RLS policy in
# the migration — enforced by tests/test_rls.py, not by anything in Python.
